### ISSUE TITLE
Testar modelos de Machine Learning | Random Forest

### ISSUE THREAD

**Issue by ardnaile** [ardnaile/ml-projeto-final#3]
Testar o modelo de [Random Forest](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html#randomforestclassifier), avaliar e anotar os resultados.

Pode ser utilizado [GridSearch CV](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) para otimizar hiperparâmetros.

Avaliar:

- [ ] Acurácia
- [ ] Recall
- [ ] Precisão

Se possível, mostrar o desempenho por meio de um gráfico.

Nomear o arquivo como ml-random-forest

**Comment by WallaceB2** [comment]
Fiquei com esse modelo.
